<?php

global $bpOptions;

// do not edit this file
// all values are set in config.php

$bpOptions['SSLcert'] = '';

$bpOptions['SSLkey'] = '';

$bpOptions['secret'] = '';

$bpOptions['verifyPos'] = true;

$bpOptions['notificationEmail'] = '';

$bpOptions['notificationURL'] = '';

$bpOptions['redirectURL'] = '';

$bpOptions['currency'] = '';

$bpOptions['physical'] = 'true';

$bpOptions['fullNotifications'] = 'true';

$bpOptions['transactionSpeed'] = 'low'; 

?>