<?php

/**
 * ©2011,2012,2013,2014 BITPAY, INC.
 * 
 * Permission is hereby granted to any person obtaining a copy of this software
 * and associated documentation for use and/or modification in association with
 * the bitpay.com service.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * 
 */

global $bpOptions;

// do not edit this file
// all values are set in config.php

$bpOptions['SSLcert'] = '';

$bpOptions['SSLkey'] = '';

$bpOptions['secret'] = '';

$bpOptions['verifyPos'] = true;

$bpOptions['notificationEmail'] = '';

$bpOptions['notificationURL'] = '';

$bpOptions['redirectURL'] = '';

$bpOptions['currency'] = '';

$bpOptions['physical'] = 'true';

$bpOptions['fullNotifications'] = 'true';

$bpOptions['transactionSpeed'] = 'low'; 

?>
